#!/bin/bash

## Environtment
export PATH="${PATH}:$HOME/.config/bspwm/bin"

#LAUNCHERS
$HOME/.config/bspwm/autostart.sh

## Configurations -------------------------------#
bspc monitor -d 1 2 3 4 5 6 7 8

bspc config border_width 1
bspc config window_gap 10
bspc config split_ratio 0.50

bspc config top_padding 30
bspc config bottom_padding 30

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer false

## Window rules -------------------------------#

# remove all rules first
bspc rule -r *:*

#fix for moving spotify to specific workspace
bspc config external_rules_command ~/.config/bspwm/bin/external_rules_command

#Floating applications
bspc rule -a termite-float state=floating follow=on focus=on
bspc rule -a KeePassXC state=floating center=true
bspc rule -a Nitrogen state=floating center=true
bspc rule -a virtualbox state=floating center=true
bspc rule -a mpv state=floating follow=on focus=on
bspc rule -a smplayer state=floating follow=on focus=on
bspc rule -a Viewnior state=floating follow=on focus=on

#open applications on specific workspaces
#bspc rule -a Chromium -o desktop=^3

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
bspc config external_rules_command pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/bin/adjust-new-window
