[greeter]
theme-name = Arc-Dark
icon-theme-name = Numix-Circle
background = /usr/share/backgrounds/12.jpeg
transition-duration = 500
transition-type = ease-in-out
font-name = Noto Sans 10
default-user-image = /usr/share/pixmaps/user.png
hide-user-image = false
indicators = ~session;~power;~clock
allow-debugging = false
screensaver-timeout = 0
laptop = false
xft-dpi = 
xft-rgba = rgb
xft-hintstyle = hintmedium

